data:
  entrega: 2
  filepath: '/home/carbajal/Documents/SaludMental/codigo_solucionadores/2026_0811/IAE_sin_agregar_entrega2_2026-08-11_15-46-54.csv'
  cv_split: 'grupo_estratificado'

  num_features:
    - GRUPO_EDAD_
    - PERSONA
    - n_intento_
    #- EDAD_
    #- DECISION
    - PRESTADOR_PUBLICO_
    - PRESTADOR_PRIVADO_
    - IAE_PREVIO_CORREGIDO_
    - DIAS_DESDE_IAE_PREVIO_
    #- STD_DIAS_ENTRE_IAES_
    #- PROMEDIO_DIAS_ENTRE_IAES_
    - CNV_
    - CNV_cant_hijos_cuando_IAE
    - CNV_edad_hijo_mayor_cuando_IAE
    - CNV_edad_hijo_menor_cuando_IAE
    #- SIV_
    #- SHARPS_
    #- RUCAF_fonasa
    #- RUCAF_no_fonasa
    #- persona_en_CNV_nro_rese_
    #- CNV_otro_progenitor_
    - ANTIPOLIOMELITICA
    - COVID 19
    - NO_CONCURRIO_CONSULTA_
    #- EH_cercano_a_IAE_EH_intento_suicidio
    #- EH_cercano_a_IAE_EH_ideacion_suicida
    - EH_cercano_a_IAE_EH_antecedente_autolesion
    - EH_cercano_a_IAE_EH_vulnerabilidad_laboral
    - EH_cercano_a_IAE_EH_vulnerabilidad_economica
    - EH_cercano_a_IAE_EH_conflicto_soporte_familiar
    - EH_cercano_a_IAE_EH_historia_trauma_infantil
    - EH_cercano_a_IAE_EH_trastorno_bipolar
    - EH_cercano_a_IAE_EH_consumo_sustancias
    - EH_cercano_a_IAE_EH_trastorno_personalidad
    - EH_cercano_a_IAE_EH_ansiedad_y_estres
    - EH_cercano_a_IAE_EH_enfermedad_oncologica
    - EH_cercano_a_IAE_EH_dias_internacion_    
    
  cat_features:
    - METODO_
    #- RUCAF_region_
    #- METODO_IAE_PREVIO_
    #- METODO_IAE_PREVIO_2_
    #- AGENDO CONSULTA ESM 7DIAS SI/NO/INTERNADO
    #- CNV_ultimo_mayor_nivel_estudio_
    #- CNV_ultimo_estado_civil_
    #- IAE_PREVIO_CORREGIDO
  target: reint_30dias_ #IAE_en_CDE_ # CAT_SUI_

filtros:
  - atributo: total_intentos_
    op: igual_a
    valor: 0
  - atributo: FECHA IAE
    op: mayor_que
    valor: 2025-11-01  
    
subgrupo_evaluacion:
  - atributo: total_intentos_
    op: mayor_que
    valor: 0
  #- atributo: RUCAF_fonasa
  #  op: igual_a
  #  valor: True   
  #- atributo: RUCAF_no_fonasa
  #  op: igual_a
  #  valor: True    
  #- atributo: RUCAF_cobertura
  #  op: es_nulo
  #  valor: 0      
  #- atributo: IAE_en_CDE_
  #  op: igual_a
  #  valor: 1    
  
  #- atributo: CNV_otro_progenitor_
  #  op: igual_a
  #  valor: True        
  #- atributo: persona_en_CNV_nro_rese_
  #  op: igual_a
  #  valor: 1                 
  #- atributo: ANTIPOLIOMELITICA
  #  op: igual_a
  #  valor: 0
  #- atributo: COVID 19
  #  op: igual_a
  #  valor: 0                 
         
experiment:
  seed: 42
  output_dir: results
  device: auto
  

