data:
  entrega: 1
  filepath: '/home/carbajal/Documents/SaludMental/codigo_solucionadores/2026_0423/IAE_agregada_entrega1_2026-04-23_06-14-11.csv'

  num_features:
    - GRUPO_EDAD_
    - Sexo
    #- NUMERO_INTENTOS_
    #- PRESTADOR_PUBLICO_
    #- PRESTADOR_PRIVADO_
    #- IAE_PREVIO_CORREGIDO
    #- CNV_
    #- CNV_ultimo_cant_hijos_
    #- SIV_
    #- SHARPS_
    # - RUCAF_cobertura
  cat_features:
    - METODO_IAE_PREVIO_
    #- IAE_PREVIO_CORREGIDO
  target: CAT_SUI_ #IAE_en_CDE_ # CAT_SUI_


experiment:
  seed: 42
  output_dir: results
  device: auto
  

